### ISSUE TITLE
no match of right hand side value: {:error, %Netler.InvokeError{communication_error: nil, dotnet_exception: nil, unreachable: true}}

### ISSUE THREAD

**Issue by wasibiit** [svan-jansson/netler#3]
```
Determining projects to restore...
/usr/local/share/dotnet/sdk/6.0.101/NuGet.targets(130,5): warning : Problem reading the cache file /Users/mac/Projects/elixir/jetzy/apps/dotnet_api/dotnet/encryption/obj/project.nuget.cache : Found invalid data while decoding. [/Users/mac/Projects/elixir/jetzy/apps/dotnet_api/dotnet/encryption/Encryption.csproj]
  All projects are up-to-date for restore.
/Users/mac/Projects/elixir/jetzy/apps/dotnet_api/dotnet/encryption/Encryption.csproj : warning Undefined: Problem reading the cache file /Users/mac/Projects/elixir/jetzy/apps/dotnet_api/dotnet/encryption/obj/project.nuget.cache : Found invalid data while decoding.
  Encryption -> /Users/mac/Projects/elixir/jetzy/apps/dotnet_api/priv/encryption/Encryption.dll

Build succeeded.

/usr/local/share/dotnet/sdk/6.0.101/NuGet.targets(130,5): warning : Problem reading the cache file /Users/mac/Projects/elixir/jetzy/apps/dotnet_api/dotnet/encryption/obj/project.nuget.cache : Found invalid data while decoding. [/Users/mac/Projects/elixir/jetzy/apps/dotnet_api/dotnet/encryption/Encryption.csproj]
/Users/mac/Projects/elixir/jetzy/apps/dotnet_api/dotnet/encryption/Encryption.csproj : warning Undefined: Problem reading the cache file /Users/mac/Projects/elixir/jetzy/apps/dotnet_api/dotnet/encryption/obj/project.nuget.cache : Found invalid data while decoding.
    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:11.40
source =>: "/Users/mac/Projects/elixir/jetzy/priv"
source =>: "/Users/mac/Projects/_build/dev/lib/dotnet_api/priv"
==> data
Compiling 1 file (.ex)
spawn: Could not cd to /Users/mac/Projects/elixir/jetzy/_build/dev/lib/dotnet_api/priv/nil
[info] Application data exited: Data.Application.start(:normal, [:ex_aws]) returned an error: shutdown: failed to start child: nil
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, %Netler.InvokeError{communication_error: nil, dotnet_exception: nil, unreachable: true}}
            (netler 0.3.2) lib/netler/client.ex:61: Netler.Client.init/1
            (stdlib 3.16.1) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.16.1) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
[info] Application ex_crypto exited: :stopped
[info] Application tds exited: :stopped
[info] Application scrivener_ecto exited: :stopped
[info] Application scrivener exited: :stopped
[info] Application securex exited: :stopped
[info] Application jason exited: :stopped
[info] Application phoenix_html exited: :stopped
[info] Application plug_cowboy exited: :stopped
[info] Application cowboy_telemetry exited: :stopped
[info] Application cowboy exited: :stopped
[info] Application ranch exited: :stopped
[info] Application cowlib exited: :stopped
[info] Application runtime_tools exited: :stopped
[info] Application csv exited: :stopped
[info] Application parallel_stream exited: :stopped
[info] Application geo_postgis exited: :stopped
[info] Application geo exited: :stopped
[info] Application poison exited: :stopped
[info] Application guardian exited: :stopped
[info] Application jose exited: :stopped
[info] Application sweet_xml exited: :stopped
[info] Application xmerl exited: :stopped
[info] Application bcrypt_elixir exited: :stopped
[info] Application inflex exited: :stopped
[info] Application comeonin exited: :stopped
[info] Application postgrex exited: :stopped
[info] Application ecto_sql exited: :stopped
[info] Application db_connection exited: :stopped
[info] Application connection exited: :stopped
[info] Application elixir_uuid exited: :stopped
[info] Application phoenix_ecto exited: :stopped
[info] Application ecto exited: :stopped
[info] Application decimal exited: :stopped
** (Mix) Could not start application data: Data.Application.start(:normal, [:ex_aws]) returned an error: shutdown: failed to start child: nil
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, %Netler.InvokeError{communication_error: nil, dotnet_exception: nil, unreachable: true}}
            (netler 0.3.2) lib/netler/client.ex:61: Netler.Client.init/1
            (stdlib 3.16.1) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.16.1) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by svan-jansson** [comment]
This is fixed in #5. Please upgrade to the latest version.
